In [1]:
# import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
df = pd.read_csv('C:\\Users\\asus\\OneDrive\\Desktop\\Python\\StudentStudyHour.csv.xls')
df

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86
25    1.3      19
26    2.6      30
27    6.1      63

In [4]:
# dropping rows which have null values
df.dropna(inplace=True,axis=0)
df
y = df['Scores']
X = df.drop('Scores',axis=1)

In [5]:
# splitting the dataframe into train and test sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)
print(X_train)
print(X_test)
scaler = StandardScaler()
scaler.fit(X_test)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
print(X_train)
print(X_test)

    Hours
20    2.7
3     8.5
1     5.1
26    2.6
12    4.5
5     1.5
14    1.1
0     2.5
19    7.4
4     3.5
8     8.3
13    3.3
9     2.7
15    8.9
27    6.1
23    6.9
6     9.2
17    1.9
11    5.9
    Hours
18    6.1
24    7.8
7     5.5
16    2.5
2     3.2
25    1.3
21    4.8
22    3.8
10    7.7
[[-0.96183597]
 [ 1.76685085]
 [ 0.16727582]
 [-1.00888229]
 [-0.11500213]
 [-1.52639186]
 [-1.71457716]
 [-1.05592862]
 [ 1.24934128]
 [-0.58546537]
 [ 1.67275821]
 [-0.67955802]
 [-0.96183597]
 [ 1.95503615]
 [ 0.63773907]
 [ 1.01410966]
 [ 2.09617513]
 [-1.33820656]
 [ 0.54364642]]
[[ 0.63773907]
 [ 1.43752658]
 [ 0.35546112]
 [-1.05592862]
 [-0.72660435]
 [-1.62048451]
 [ 0.02613685]
 [-0.4443264 ]
 [ 1.39048026]]

In [6]:
lr = LinearRegression()
model = lr.fit(X_train,y_train)
y_pred = model.predict(X_test)
df = pd.DataFrame({'y_test':y_test,'y_pred':y_pred})
df
print(mean_squared_error(y_test,y_pred))

39.23322844116153